name: Generate & Publish VRChat API Python SDK

# allow pushing back to your repo and/or using OIDC for Trusted Publishing
permissions:
  contents: write
  id-token: write   # only needed if you ever switch to “trusted publishing” w/o password

on:
  repository_dispatch:
    types: [spec_release]
  workflow_dispatch:

jobs:
  generate-and-publish:
    name: Generate & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      # 1) Checkout the repo (with your PAT)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          fetch-depth: 0

      # 2) Install & pin OpenAPI Generator
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v16-${{ hashFiles('**/generate.sh') }}
          restore-keys: |
            ${{ runner.os }}-node-v16

      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli

      - name: Pin OpenAPI Generator version
        run: npx @openapitools/openapi-generator-cli version-manager set 6.2.1

      # 3) Generate your Python client
      - name: Generate SDK Client
        run: bash ./generate.sh

      # 4) Build & package with Python
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build & twine
        run: python -m pip install --upgrade pip build twine

      - name: Extract SDK version
        id: get_version
        run: |
          # this reads VERSION from your updated setup.py
          VERSION=$(grep '^VERSION =' setup.py | cut -d'"' -f2)
          echo "SDK_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Show SDK version
        run: echo "Releasing SDK version ${{ env.SDK_VERSION }}"

      # 5) (Optional) Commit generated client back into main
      - name: Commit generated client to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "Upgrade vrchat-api-client to spec ${{ env.SDK_VERSION }}"
          git push origin main

      - name: Build distributions
        run: python -m build --sdist --wheel --outdir dist/

      # 6) Publish to PyPI under the new project name
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: "__token__"
          password: ${{ secrets.PYPI_API_TOKEN }}
